### ISSUE TITLE
why do you use ZeroMQ

### ISSUE THREAD

**Issue by fizz12344321** [fair-acc/opencmw-java#194]
hi, I am reading your project, why do you use ZeroMQ in your project instead of other message queues like Kafka, RabbitMQ... can you tell me about your purpose, the cons and pros of ZeroMQ, thank you so much

**Comment by RalphSteinhagen** [comment]
@fizz12344321 hope this was helpful and answered your question. 

Meanwhile, since this is not a bug, I'll transfer this to the new discussion.

May I ask the background of your project?
